development:
  adapter: postgresql
  database: githacking_development
  
test: &test
  adapter: postgresql
  database: githacking_test

production:
  adapter: postgresql
  database: githacking

cucumber:
  <<: *test