development:
  adapter: postgresql
  database: githacking_development
  username: josiah
  
test:
  adapter: postgresql
  database: githacking_test

production:
  adapter: postgresql
  database: githacking
