development:
    client_id: [client_id]
    secret: [hush_hush]
    redirect_uri: http://githacking.dev/users/oauth
  
test: 
    client_id: [client_id]
    secret: [hush_hush]
    redirect_uri: http://githacking.dev/users/oauth

production:
    client_id: [client_id]
    secret: [hush_hush]
    redirect_uri: http://githacking.com
